name: "Can I deploy with other applications?"
description: "Checks if multiple applications are compatible"
branding:
  icon: "check"
  color: "green"
inputs:
  pact_broker:
    description: "The url of your pact broker"
    required: true
  pact_broker_token:
    description: "Your pact broker token"
    required: true
  applications:
    description: "A (strnig) comma seperated list of name:[version|latest] [number|tag]"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
